using Godot;

/// <summary>
/// A course whose shape was measured rather than composed: the height and heading at every
/// point come from a sampled profile instead of from summed sine layers.
///
/// Block Island is built this way, from the real road over the real island. The samples are
/// generated by <c>build_block_island.py</c>, which reads the LiDAR heightfield and the road
/// centrelines out of the <c>block-island-simulator</c> repo and writes
/// <c>Resources/Design/BlockIsland.tres</c>. Nothing here loads that repo at runtime — the
/// numbers are baked, and the generator is the only thing that ever needs it.
///
/// Everything downstream — TerrainManager, SceneryManager, GameCamera, PlayerManager — asks a
/// CourseDesign for <see cref="HillAt"/> and <see cref="CurveAt"/> and never learns which
/// kind it got.
///
/// THE PROFILE IS NOT THE ISLAND AT 1:1, and the three places it departs are recorded on the
/// resource itself rather than left for someone to rediscover. See
/// <see cref="VerticalExaggeration"/>, <see cref="CurveScale"/> and <see cref="SourceNote"/>.
/// </summary>
[Tool]
[GlobalClass]
public partial class MeasuredCourse : CourseDesign
{
    // ── The samples ──────────────────────────────
    [ExportGroup("Measured profile")]

    /// <summary>Metres between consecutive samples. The profile is evenly spaced by construction.</summary>
    [Export(PropertyHint.Range, "1,50,0.5")] public float SampleSpacing { get; set; } = 10f;

    /// <summary>
    /// Road height in metres at each sample, already exaggerated, with the start line at 0.
    /// Descending, so these go negative.
    /// </summary>
    [Export] public float[] Heights { get; set; } = System.Array.Empty<float>();

    /// <summary>
    /// Road heading at each sample, in radians, as a deviation from the course's own slowly
    /// turning baseline. Same units and meaning as the sine version's CurveAt.
    /// </summary>
    [Export] public float[] Headings { get; set; } = System.Array.Empty<float>();

    // ── What was done to the measurements ────────
    [ExportGroup("Provenance")]

    /// <summary>
    /// What the heights were multiplied by. Recorded so the resource can always be read back
    /// against the survey.
    ///
    /// The island tops out at 63.7 m and its best sustained descent is 2.5%, against the 8%
    /// this game's physics is built around — at the real grade a rider settles at 31 km/h,
    /// never reaches the 15.8 m/s speed-wobble onset, and the course has no way to end badly.
    /// Doubling the relief puts the steepest 600 m at 9.6% and the average at 5.8%, which
    /// brackets Frogwood.
    /// </summary>
    [Export] public float VerticalExaggeration { get; set; } = 2f;

    /// <summary>
    /// What the headings were multiplied by, after the road's slowly turning baseline was
    /// subtracted.
    ///
    /// Two separate problems, both from the road model rather than from the data. The ribbon
    /// draws a point at <c>CurveAt(z) * lookAhead</c>, so heading is only meaningful as a
    /// small angle: the real road swings 66 degrees off its mean, which would throw the far
    /// end of the road hundreds of metres sideways. And the camera here always sits behind
    /// the rider, so a road's absolute bearing is not observable anyway — only how it bends
    /// relative to where it was pointing a moment ago.
    ///
    /// So the baseline is removed (that part costs nothing you could see) and what is left is
    /// scaled to an amplitude this projection can draw. Where the bends fall and which way
    /// they go is measured; how hard they bite is not.
    /// </summary>
    [Export] public float CurveScale { get; set; } = 1f;

    /// <summary>
    /// Distance to open water at each sample, in metres. Spring Street is 40 m from the
    /// Atlantic where it leaves the Southeast Light and 770 m from it further down, so a
    /// single number would either put the sea out of sight for the whole run or drag it
    /// inland to somewhere it is not.
    /// </summary>
    [Export] public float[] ShoreSamples { get; set; } = System.Array.Empty<float>();

    /// <summary>Where the profile came from, in one line. Written by the generator.</summary>
    [Export(PropertyHint.MultilineText)] public string SourceNote { get; set; } = "";

    // ═══════════════════════════════════════════
    //  THE COURSE
    // ═══════════════════════════════════════════

    /// <summary>
    /// Height at <paramref name="z"/>, linearly interpolated between samples.
    ///
    /// Past the last sample the road keeps descending on the grade it finished at, rather than
    /// flattening or falling off a cliff: the finish banner sits at Length, but the ribbon is
    /// drawn a few hundred metres beyond it and the rider can still be rolling when it does.
    /// </summary>
    public override float HillAt(float z)
    {
        if (Heights == null || Heights.Length == 0) return base.HillAt(z);
        if (z <= 0f) return Heights[0];

        float f = z / SampleSpacing;
        int i = (int)f;
        if (i >= Heights.Length - 1)
        {
            // Extend on the closing grade.
            int last = Heights.Length - 1;
            float grade = last > 0 ? (Heights[last] - Heights[last - 1]) / SampleSpacing : 0f;
            return Heights[last] + grade * (z - last * SampleSpacing);
        }
        return Mathf.Lerp(Heights[i], Heights[i + 1], f - i);
    }

    /// <summary>How far the water is at <paramref name="z"/>, interpolated between samples.</summary>
    public override float ShoreAt(float z)
    {
        if (ShoreSamples == null || ShoreSamples.Length == 0) return base.ShoreAt(z);
        if (z <= 0f) return ShoreSamples[0];

        float f = z / SampleSpacing;
        int i = (int)f;
        if (i >= ShoreSamples.Length - 1) return ShoreSamples[ShoreSamples.Length - 1];
        return Mathf.Lerp(ShoreSamples[i], ShoreSamples[i + 1], f - i);
    }

    /// <summary>Heading at <paramref name="z"/>. Straight before the start and after the end.</summary>
    public override float CurveAt(float z)
    {
        if (Headings == null || Headings.Length == 0) return base.CurveAt(z);
        if (z <= 0f) return Headings[0];

        float f = z / SampleSpacing;
        int i = (int)f;
        if (i >= Headings.Length - 1) return Headings[Headings.Length - 1];
        return Mathf.Lerp(Headings[i], Headings[i + 1], f - i);
    }
}
